#!/bin/bash



echo "----- DOTFILE DEPLOY STARTING -----"
git pull

mkdir -p nvim ~/.config/nvim
mkdir -p nvim ~/.config/tmux

cp -rv nvim ~/.config/
cp -v zsh/.zshrc ~
cp -rv tmux/tmux.conf ~/.config/tmux/

echo "  -> All configs copied."

echo "----- DOTFILE DEPLOY FINISHED -----"
