#!/bin/bash



echo "----- DOTFILE DEPLOY STARTING -----"
git pull

cp -rv nvim ~/.config/
cp -v zsh/.zshrc ~
cp -rv tmux/tmux.conf ~/.config/

echo "  -> All configs copied."

echo "----- DOTFILE DEPLOY FINISHED -----"
