#!/bin/bash

echo "----- DOTFILE FETCH STARTING -----"

# Neovim
cp -r ~/.config/nvim .
rm -rf nvim/.git/

# git config
cp ~/.gitmessage .

echo "  -> All configs sync'd."

echo "----- DOTFILE FETCH FINISHED -----"
