#!/bin/bash

echo "----- DOTFILE FETCH STARTING -----"

# Neovim
cp -rv ~/.config/nvim .
rm -rf nvim/.git/

# zsh
cp -v ~/.zshrc zsh/

# tmux
cp -rv ~/.config/tmux .

# git config
cp ~/.gitmessage .

echo "  -> All configs sync'd."

echo "----- DOTFILE FETCH FINISHED -----"
